%%{init: {'flowchart': {'useMaxWidth': false, 'nodeSpacing': 25, 'rankSpacing': 40}} }%%
flowchart TB
    B0["Component 2.A — Environmental Factors"]

    B1["Chapter 1: Products and technology"]
    B2["Chapter 2: Natural environment and human-made changes to environment"]
    B3["Chapter 3: Support and relationships"]

    B0 --> B1
    B0 --> B2
    B0 --> B3
