%%{init: {'flowchart': {'useMaxWidth': false, 'nodeSpacing': 25, 'rankSpacing': 40}} }%%
flowchart TB
    A0["Component 1.B — Activities & Participation"]

    A1["Chapter 1: Learning and applying knowledge"]
    A2["Chapter 2: General tasks and demands"]
    A3["Chapter 3: Communication"]
    A4["Chapter 4: Mobility"]
    A5["Chapter 5: Self-care"]
    A6["Chapter 6: Domestic life"]
    A7["Chapter 7: Interpersonal interactions and relationships"]
    A8["Chapter 8: Major life areas"]
    A9["Chapter 9: Community, social and civic life"]

    A0 --> A1
    A0 --> A2
    A0 --> A3
    A0 --> A4
    A0 --> A5
    A0 --> A6
    A0 --> A7
    A0 --> A8
    A0 --> A9
